# Inserção de dados...
print("Digite o seu nome:")
MyName = str(input())
print("Digite a sua altura:")
MyHeigh = float(input())
print("Digite a sua idade")
MyAge = int(input())
print("Digite sua data de nascimento")
data = float(input())
print ("Digite seu cantor favorito")
cantor = input()
print ("Digite seu numero de celular")
celular = int(input ())
print ("Digite onde nasceu")
lugar = input()
#Exibição do conteúdo das variáveis...
print("Meu nome é", MyName, ".")
print("Minha altura é de", MyHeigh, "metros")
print("Minha idade é", MyAge, "anos")
print("Nasceu:", data, )
print("Cantos fav:", cantor, )
print("Número de celular:", celular, )
print("Lugar onde nasceu:", lugar, )